# **19CSE305: MACHINE LEARNING LAB 2**

ROLL NUMBER: CB.EN.U4CSE20314

## Python Basic Exercises

1. Get the values P,t,R from user and calculate compound interest. Formula to calculate compound interest annually is given by: 
        A = P(1+R/100)*t
        CI = A – P
        Input : Principle, Time, Rate
        Output : Compound Interest
2. Given a list of strings (Entered by the user), write program to get a percentage share of each word in the strings list.
        percentage = (Occurrence of a word / Total words) * 100
3. Check if  the binary representation of a number is Palindrome or not. Given an integer ‘n’ (entered by the user), write a Python function that returns true if binary representation of 'x' is palindrome and false if not.
4. Write a program to check if all digits of a number divide it. Given a number n (entered by the user), find whether all digits of n divide it or not.
5. Given a list of numbers (entered by the user), write a program to find the second largest number in that list.
        Input: [1, 2, 3, 4 ,5]
        Output: 4

## Numpy Basic Exercises

1. Create a 3D array of shape 4*5*2 that contains random decimal numbers between 1 and 10.
2. Create a randomly created 1D array and Convert it to a 2D array with 2 rows.
3. Given a NumPy array of temperature values, convert the values of Centigrade degrees into Fahrenheit degrees. 
4. Write a NumPy program to count the number of dimensions, number of elements and number of bytes for each element in a given array.
5. Write a NumPy program to extract third and second elements of the first and second rows from a given (3x4) array

##Python Basic Exercises

1.

In [4]:
P=int(input())
t=int(input())
R=int(input())
A=P*((1+R/100))**t
CI=A-P
print(f"Compound Interest for the P={P} T={t} R={R} is {CI}")

1000
100
10
Compound Interest for the P=1000 T=100 R=10 is 13779612.339822382


# 2


In [58]:
str1=str(input())
x=str.split(str1)
print(x)
count=0
for i in range(len(x)):
    count=0
    for j in range(len(x)):
        if(x[i]==x[j]):
            count=count+1
    print(f'The percentage of {x[i]} is {(count/len(x))*100}')

Hi guys i am Devasunder Hi
['Hi', 'guys', 'i', 'am', 'Devasunder', 'Hi']
The percentage of Hi is 33.33333333333333
The percentage of guys is 16.666666666666664
The percentage of i is 16.666666666666664
The percentage of am is 16.666666666666664
The percentage of Devasunder is 16.666666666666664
The percentage of Hi is 33.33333333333333


# 3

In [16]:
import math
num= int(input())
x= bin(num)
k=0
st=''
st=st+x
st=st[2:]
print(f'The binary represenation is {x}')
for i in range(int((len(st)/2))):
    if(st[i]==st[len(st)-1-i]):
        pass
    else:
        k=1
        print('Not a palindrome')
if (k==0):
    print("Its a palindrome")

33
The binary represenation is 0b100001
Its a palindrome


# 4


In [55]:
import string
num=int(input())
x=str(num)
sup=0
for i in range(len(x)):
    if(int(x[i])==0):
        print("Not dividable")
        break
    elif(num%int(x[i])==0):
        pass
    else:
        print("Not dividable")
        sup=1
if (sup==0):
    print("dividable")

99
dividable


# 5


In [39]:
import math
lst=[]
print("Enter the number of elements:")
x=int(input())
for i in range(x):
    lst.append(int(input()))
print(lst)
mx=max(lst)
print(mx)
for i in range(len(lst)):
    print(i)
    if(lst[i]==mx):
        lst[i]=0
mx=max(lst)
print(f'The second maximum is {mx}')

Enter the number of elements:
6
10
5
60
25
46
85
[10, 5, 60, 25, 46, 85]
85
0
1
2
3
4
5
The second maximum is 60


# Numpy basic exercises

1

In [77]:
import numpy as np
darr = np.random.randint(1, 10, size=(4, 5, 2))
print(darr)

[[[6 1]
  [6 4]
  [2 9]
  [6 4]
  [5 1]]

 [[2 9]
  [5 4]
  [8 9]
  [2 5]
  [2 7]]

 [[5 9]
  [2 3]
  [2 6]
  [9 5]
  [4 6]]

 [[2 5]
  [6 7]
  [2 5]
  [4 4]
  [7 7]]]


# 2

In [62]:
import numpy as np
list2=[50,10,30,40]
x=np.array(list2)
print(x)
y=np.reshape(x,(2,2))
print(y)

[50 10 30 40]
[[50 10]
 [30 40]]


# 3

In [ ]:
import numpy as np
cent=[32,35,37,40]
c=np.array(cent)
print(c)
print(np.round((9*c/5 + 32),2))

# 4

In [2]:
x1=np.array([[20,10,30,50],[40,20,30,10]])
print(f'Number of dimensions are {x1.ndim}')
print(f'Number of elements are {x1.size}')
for i in range(x1.size-1):
    print(f'number of bytes of each element are {x1[].itemsize}.')




SyntaxError: f-string: invalid syntax (1731945938.py, line 5)

# 5

In [3]:

x2=np.array[[10,20,30],[10,20,30,40]]


NameError: name 'np' is not defined